-- Table structure: Assumes database is created and is being USEed

CREATE TABLE IF NOT EXISTS g503sn_tbl (
  `id` int(8) NOT NULL AUTO_INCREMENT,
  `model` int(2) NOT NULL DEFAULT '0',
  `serialnumber` int(4) NOT NULL DEFAULT '0',
  `frame` varchar(25) DEFAULT NULL,
  `engine` varchar(25) DEFAULT NULL,
  `body` varchar(25) DEFAULT NULL,
  `bodytype` varchar(50) DEFAULT NULL,
  `hood` varchar(25) DEFAULT NULL,
  `factory` varchar(50) DEFAULT NULL,
  `weight` varchar(50) DEFAULT NULL,
  `plateorigin` varchar(50) DEFAULT NULL,
  `plate` varchar(50) DEFAULT NULL,
  `dateofmanufacture` date NOT NULL DEFAULT '0000-00-00',
  `dateofacquisition` date NOT NULL DEFAULT '0000-00-00',
  `firstname` varchar(50) DEFAULT NULL,
  `lastname` varchar(50) DEFAULT NULL,
  `email` varchar(50) DEFAULT NULL,
  `privatemessage` int(1) NOT NULL DEFAULT '0',
  `phone` varchar(50) DEFAULT NULL,
  `city` varchar(50) DEFAULT NULL,
  `state` varchar(50) DEFAULT NULL,
  `country` int(2) NOT NULL DEFAULT '0',
  `password` varchar(50) DEFAULT NULL,
  `imagesmall` varchar(50) DEFAULT NULL,
  `imagemedium` varchar(50) DEFAULT NULL,
  `imagelarge` varchar(50) DEFAULT NULL,
  `blurb` text,
  `details` text,
  `url` varchar(128) DEFAULT NULL,
  `topicid` int(4) NOT NULL DEFAULT '0',
  `ip` varchar(50) DEFAULT NULL,
  `spotlightcount` int(4) NOT NULL DEFAULT '0',
  `active` int(1) NOT NULL DEFAULT '1',
  `datecreated` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `datemodified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1001 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ;
